image:
  file: .gitpod.Dockerfile
tasks:
  - before: >
      source ~/.bashrc
    init: >
      sbt update
ports:
  - port: 8212
    onOpen: ignore
vscode:
  extensions:
    - scala-lang.scala
    - scalameta.metals
